name: Project automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  sync-project-issues:
    name: Add issue/pull requests to project
    runs-on: ubuntu-latest
    env:
      GH_PROJECT_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install @actions/github date-fns
          node scripts/project-automation.js
